### ISSUE TITLE
python errors

### ISSUE THREAD

**Issue by victorjulien** [jasonish/suricata-verify#16]
Last nights push broke several of my builders:

CentOS6, Fedora25 and 26 all give:
<pre>
$ python3 ../suricata-verify/run.py
Traceback (most recent call last):
  File "../suricata-verify/run.py", line 763, in <module>
    sys.exit(main())
  File "../suricata-verify/run.py", line 734, in main
    cwd, dirpath, outdir, suricata_config, args.verbose)
  File "../suricata-verify/run.py", line 320, in __init__
    self.suricata_config.load_config(self.get_suricata_yaml_path())
  File "../suricata-verify/run.py", line 181, in load_config
    for line in output.split("\n"):
TypeError: 'str' does not support the buffer interface
ERROR: Job failed: exit code 1
</pre>

**Comment by jasonish** [comment]
Sorry about that, just Python 3 broke. Fixed in c61b80fd3c56e7e06705c35483aeb5082456c1b2.

**Comment by victorjulien** [comment]
Fix confirmed, thanks!
